---
environment: production

hostname: www.example.org
hostpath: ""

image:
  repository: gcr.io/planet-4-151612/openresty
  tag: latest
  pullPolicy: Always
fastcgi:
  redis: false
service:
  type: ClusterIP
  port: 80
healthProbes:
  enabled: true
  livenessDelay: 5
  livenessPeriod: 10
  readinessDelay: 5
  readinessPeriod: 10
geoip:
  enabled: false
minReplicaCount: 2
maxReplicaCount: 2
resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
targetCPUUtilizationPercentage: 1000 # * targetCPUUtilizationPercentage. 200m * 500 = 1 CPU

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

ingressProduction:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  tls: []

pagespeed:
  redis:
    enabled: false
  enabled: false

nodeSelector: {}

tolerations: []
