---
environment: production

hostname: www.example.org
hostpath: ""

image:
  repository: gcr.io/planet-4-151612/openresty
  tag: latest
  pullPolicy: Always
fastcgi:
  redis: false
service:
  type: ClusterIP
  port: 80
healthProbes:
  enabled: true
  livenessDelay: 5
  livenessPeriod: 10
  readinessDelay: 5
  readinessPeriod: 10

minReplicaCount: 1
maxReplicaCount: 2

resources:
  requests:
    memory: "32Mi"
    cpu: "10m" # * targetCPUUtilizationPercentage. 10m * 5000% = .5 CPU
  limits:
    memory: "64Mi"
    cpu: "100m"
targetCPUUtilizationPercentage: 5000 # Scale up when pod uses .5 cores

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

pagespeed:
  redis:
    enabled: false
  enabled: false

openresty:
  geoip:
    enabled: false
    accountid: ""
    license: ""

  cloudflare:
    enabled: false

nodeSelector: {}

tolerations: []
