{{- if .Values.nginxingress.enabled -}}
{{- $fullName := include "fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-nginx
  labels:
    app: {{ template "name" . }}
    chart: {{ template "static.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.nginxingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.nginxingress.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    {{- if .Values.hosttls }}
    secretName: {{ .Values.hostname }}
    {{- end }}
  {{- if .Values.nginxingress.hosts }}
  {{- range .Values.nginxingress.hosts }}
  - hosts:
    - {{ .name }}
  {{- if .tls }}
    secretName: {{ .name }}-tls
  {{- end }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /{{ .Values.hostpath | default "" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- if .Values.nginxingress.hosts }}
    {{ range $i, $host := .Values.nginxingress.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          - path: /{{ $host.path | default "" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{- end }}
    {{- end }}
{{- end }}
