apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" . }}
spec:
  minAvailable: {{ sub .Values.minReplicaCount 1 }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}